# Site metadata
site:
  name: "null docs"
  tagline: "Beautiful documentation, instantly."
  favicon: "/favicon.ico"
  url: "https://docs.myproject.com"
  repo: "https://github.com/Nu11ified/docs-template"

# Theming
theme:
  colors:
    primary: "#6366f1"
    secondary: "#ec4899"
    background: "#f8f9fa"
    surface: "#ffffff"
    text: "#0f172a"
    dark:
      background: "#0f172a"
      surface: "#1e293b"
      text: "#f8fafc"
  fonts:
    heading: "Inter"
    body: "Inter"
    code: "JetBrains Mono"
  radius: "lg"

# Landing page sections
landing:
  sections:
    - type: hero
      badge: "Open Source"
      title: "Documentation that just works."
      subtitle: "Beautiful, fast, and fully customizable docs — powered by Bun, ElysiaJS, and MDX. One YAML file to configure everything."
      primaryCTA:
        label: "Get Started"
        href: "/docs"
      secondaryCTA:
        label: "View on GitHub"
        href: "https://github.com/Nu11ified/docs-template"
    - type: features
      title: "Built for developers"
      columns: 3
      items:
        - icon: "zap"
          title: "Lightning Fast"
          description: "Sub-millisecond responses. Bun runtime + ElysiaJS means your docs load before your users blink."
        - icon: "code"
          title: "MDX Powered"
          description: "Write in Markdown, embed React components. Shiki syntax highlighting with zero client-side JS."
        - icon: "search"
          title: "Instant Search"
          description: "Server-side FlexSearch indexes every page. No Algolia, no client bundle, just fast results."
        - icon: "palette"
          title: "One YAML Config"
          description: "Colors, fonts, sections, navigation — everything is driven by a single site.yaml file."
        - icon: "shield"
          title: "Type-safe"
          description: "Zod-validated configuration catches errors before they reach production. No surprises."
        - icon: "rocket"
          title: "Deploy Anywhere"
          description: "Docker, Fly.io, Railway, or bare metal. It's just a Bun server — runs everywhere."
    - type: faq
      title: "FAQ"
      items:
        - question: "How do I get started?"
          answer: "Clone the repo, run bun install, edit site.yaml, and run bun dev. Your docs site is ready in under 5 minutes."
        - question: "Can I use custom React components in docs?"
          answer: "Yes — docs are written in MDX, so you can import and use any React component directly in your markdown files."
        - question: "Is server-side search good enough?"
          answer: "For most doc sites, absolutely. FlexSearch indexes at build time and serves results in microseconds."
        - question: "Can I deploy this anywhere?"
          answer: "Yes — anywhere that runs Bun. Docker, Fly.io, Railway, or any VPS. It's just a Bun server."
    - type: cta
      title: "Ship your docs today."
      description: "Clone, configure, deploy. No config hell."
      button:
        label: "Read the Docs"
        href: "/docs"

# Docs configuration
docs:
  defaultVersion: "v1"
  versions:
    - label: "v1"
      path: "v1"
  search:
    enabled: true
    placeholder: "Search docs..."
  sidebar:
    collapsible: true
  toc:
    minHeading: 2
    maxHeading: 3

# Top navigation
nav:
  links:
    - label: "Docs"
      href: "/docs"
    - label: "GitHub"
      href: "https://github.com/Nu11ified/docs-template"
      external: true
